name: Deploy

on:
  pull_request:
    branches:
    - main

env:
  WEBAPP_NAME_STAGING: moviematchwebstg
  API_URL_STAGING: https://moviematchapi-staging.azurewebsites.net/api
  REACT_APP_AUTH_REDIRECT_URI_STAGING: https://moviematchwebstg.azurewebsites.net/
  WEBAPP_NAME_PRODUCTION: moviematchweb
  API_URL_PRODUCTION: https://moviematchapi.azurewebsites.net/api
  REACT_APP_AUTH_REDIRECT_URI_PRODUCTION: https://moviematchweb.azurewebsites.net/
  WEBAPP_PACKAGE_PATH: ./build

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run Jest unit tests
        shell: bash
        env:
          CI: true
          REACT_APP_API_URL: ${{ env.API_URL_STAGING }}
          REACT_APP_CLIENT_ID: ${{secrets.REACT_APP_CLIENT_ID}}
          REACT_APP_AZURE_AD_TENANT_ID: ${{secrets.AZURE_AD_TENANT_ID}}
          REACT_APP_AUTH_REDIRECT_URI: ${{ env.REACT_APP_AUTH_REDIRECT_URI_STAGING }}
        run: |
          npm ci
          npm run build --if-present
          npm test

      - name: Login to Azure
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy infrastructure
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ secrets.AZURE_RG }}
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template: ./bicep/main.bicep
          parameters: appNameStaging=${{ env.WEBAPP_NAME_STAGING }} appNameProduction=${{ env.WEBAPP_NAME_PRODUCTION }}

      - name: Deploy staging webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME_STAGING }}
          package: ${{ env.WEBAPP_PACKAGE_PATH }}

#      - name: Deploy production webapp
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: ${{ env.WEBAPP_NAME_PRODUCTION }}
#          package: ${{ env.WEBAPP_PACKAGE_PATH }}
