name: Test

on:
  pull_request:
    branches:
    - main

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Run Jest unit tests
        shell: bash
        env:
          CI: true
        run: |
          npm ci
          npm run build --if-present
          npm test

